# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos.python.wallet import replies_pb2 as wallet_dot_replies__pb2
from protos.python.wallet import requests_pb2 as wallet_dot_requests__pb2


class WalletServiceStub(object):
    """The wallets service definition.
  """

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.GetStatus = channel.unary_unary(
            "/qbit.WalletService/GetStatus",
            request_serializer=wallet_dot_requests__pb2.GetStatusRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetStatusReply.FromString,
        )
        self.Authenticate = channel.unary_unary(
            "/qbit.WalletService/Authenticate",
            request_serializer=wallet_dot_requests__pb2.AuthenticateRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.AuthenticateReply.FromString,
        )
        self.VerifyAuthenticate = channel.unary_unary(
            "/qbit.WalletService/VerifyAuthenticate",
            request_serializer=wallet_dot_requests__pb2.VerifyAuthenticateRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.VerifyAuthenticateReply.FromString,
        )
        self.CheckAuthenticate = channel.unary_unary(
            "/qbit.WalletService/CheckAuthenticate",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.CheckAuthenticateReply.FromString,
        )
        self.RefreshAuthenticate = channel.unary_unary(
            "/qbit.WalletService/RefreshAuthenticate",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.RefreshAuthenticateReply.FromString,
        )
        self.SetWalletPermissions = channel.unary_unary(
            "/qbit.WalletService/SetWalletPermissions",
            request_serializer=wallet_dot_requests__pb2.SetWalletPermissionsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.SetWalletPermissionsReply.FromString,
        )
        self.GetUser = channel.unary_unary(
            "/qbit.WalletService/GetUser",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetUserReply.FromString,
        )
        self.GetPartner = channel.unary_unary(
            "/qbit.WalletService/GetPartner",
            request_serializer=wallet_dot_requests__pb2.GetPartnerRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetPartnerReply.FromString,
        )
        self.GetPartnerServices = channel.unary_unary(
            "/qbit.WalletService/GetPartnerServices",
            request_serializer=wallet_dot_requests__pb2.GetPartnerServicesRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetPartnerServicesReply.FromString,
        )
        self.GetPartnerDebts = channel.unary_unary(
            "/qbit.WalletService/GetPartnerDebts",
            request_serializer=wallet_dot_requests__pb2.GetPartnerDebtsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetPartnerDebtsReply.FromString,
        )
        self.CreateWalletPayments = channel.unary_unary(
            "/qbit.WalletService/CreateWalletPayments",
            request_serializer=wallet_dot_requests__pb2.CreateWalletPaymentsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.CreateWalletPaymentsReply.FromString,
        )
        self.GetPayment = channel.unary_unary(
            "/qbit.WalletService/GetPayment",
            request_serializer=wallet_dot_requests__pb2.GetPaymentRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetPaymentReply.FromString,
        )
        self.CancelPayment = channel.unary_unary(
            "/qbit.WalletService/CancelPayment",
            request_serializer=wallet_dot_requests__pb2.CancelPaymentRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.CancelPaymentReply.FromString,
        )
        self.ModifyPayment = channel.unary_unary(
            "/qbit.WalletService/ModifyPayment",
            request_serializer=wallet_dot_requests__pb2.ModifyPaymentRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.ModifyPaymentReply.FromString,
        )
        self.VerifyPayment = channel.unary_unary(
            "/qbit.WalletService/VerifyPayment",
            request_serializer=wallet_dot_requests__pb2.VerifyPaymentRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.VerifyPaymentReply.FromString,
        )
        self.GetPaymentTransactions = channel.unary_unary(
            "/qbit.WalletService/GetPaymentTransactions",
            request_serializer=wallet_dot_requests__pb2.GetPaymentTransactionsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetPaymentTransactionsReply.FromString,
        )
        self.GetWallet = channel.unary_unary(
            "/qbit.WalletService/GetWallet",
            request_serializer=wallet_dot_requests__pb2.GetWalletRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetWalletReply.FromString,
        )
        self.GetWalletPayments = channel.unary_unary(
            "/qbit.WalletService/GetWalletPayments",
            request_serializer=wallet_dot_requests__pb2.GetWalletPaymentsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetWalletPaymentsReply.FromString,
        )
        self.GetWalletDebts = channel.unary_unary(
            "/qbit.WalletService/GetWalletDebts",
            request_serializer=wallet_dot_requests__pb2.GetWalletDebtsRequest.SerializeToString,
            response_deserializer=wallet_dot_replies__pb2.GetWalletDebtsReply.FromString,
        )


class WalletServiceServicer(object):
    """The wallets service definition.
  """

    def GetStatus(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Authenticate(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerifyAuthenticate(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckAuthenticate(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefreshAuthenticate(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetWalletPermissions(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUser(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPartner(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPartnerServices(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPartnerDebts(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateWalletPayments(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPayment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelPayment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ModifyPayment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerifyPayment(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPaymentTransactions(self, request, context):
        """TODO: Implement
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWallet(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWalletPayments(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWalletDebts(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=wallet_dot_requests__pb2.GetStatusRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetStatusReply.SerializeToString,
        ),
        "Authenticate": grpc.unary_unary_rpc_method_handler(
            servicer.Authenticate,
            request_deserializer=wallet_dot_requests__pb2.AuthenticateRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.AuthenticateReply.SerializeToString,
        ),
        "VerifyAuthenticate": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyAuthenticate,
            request_deserializer=wallet_dot_requests__pb2.VerifyAuthenticateRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.VerifyAuthenticateReply.SerializeToString,
        ),
        "CheckAuthenticate": grpc.unary_unary_rpc_method_handler(
            servicer.CheckAuthenticate,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=wallet_dot_replies__pb2.CheckAuthenticateReply.SerializeToString,
        ),
        "RefreshAuthenticate": grpc.unary_unary_rpc_method_handler(
            servicer.RefreshAuthenticate,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=wallet_dot_replies__pb2.RefreshAuthenticateReply.SerializeToString,
        ),
        "SetWalletPermissions": grpc.unary_unary_rpc_method_handler(
            servicer.SetWalletPermissions,
            request_deserializer=wallet_dot_requests__pb2.SetWalletPermissionsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.SetWalletPermissionsReply.SerializeToString,
        ),
        "GetUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=wallet_dot_replies__pb2.GetUserReply.SerializeToString,
        ),
        "GetPartner": grpc.unary_unary_rpc_method_handler(
            servicer.GetPartner,
            request_deserializer=wallet_dot_requests__pb2.GetPartnerRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetPartnerReply.SerializeToString,
        ),
        "GetPartnerServices": grpc.unary_unary_rpc_method_handler(
            servicer.GetPartnerServices,
            request_deserializer=wallet_dot_requests__pb2.GetPartnerServicesRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetPartnerServicesReply.SerializeToString,
        ),
        "GetPartnerDebts": grpc.unary_unary_rpc_method_handler(
            servicer.GetPartnerDebts,
            request_deserializer=wallet_dot_requests__pb2.GetPartnerDebtsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetPartnerDebtsReply.SerializeToString,
        ),
        "CreateWalletPayments": grpc.unary_unary_rpc_method_handler(
            servicer.CreateWalletPayments,
            request_deserializer=wallet_dot_requests__pb2.CreateWalletPaymentsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.CreateWalletPaymentsReply.SerializeToString,
        ),
        "GetPayment": grpc.unary_unary_rpc_method_handler(
            servicer.GetPayment,
            request_deserializer=wallet_dot_requests__pb2.GetPaymentRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetPaymentReply.SerializeToString,
        ),
        "CancelPayment": grpc.unary_unary_rpc_method_handler(
            servicer.CancelPayment,
            request_deserializer=wallet_dot_requests__pb2.CancelPaymentRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.CancelPaymentReply.SerializeToString,
        ),
        "ModifyPayment": grpc.unary_unary_rpc_method_handler(
            servicer.ModifyPayment,
            request_deserializer=wallet_dot_requests__pb2.ModifyPaymentRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.ModifyPaymentReply.SerializeToString,
        ),
        "VerifyPayment": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyPayment,
            request_deserializer=wallet_dot_requests__pb2.VerifyPaymentRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.VerifyPaymentReply.SerializeToString,
        ),
        "GetPaymentTransactions": grpc.unary_unary_rpc_method_handler(
            servicer.GetPaymentTransactions,
            request_deserializer=wallet_dot_requests__pb2.GetPaymentTransactionsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetPaymentTransactionsReply.SerializeToString,
        ),
        "GetWallet": grpc.unary_unary_rpc_method_handler(
            servicer.GetWallet,
            request_deserializer=wallet_dot_requests__pb2.GetWalletRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetWalletReply.SerializeToString,
        ),
        "GetWalletPayments": grpc.unary_unary_rpc_method_handler(
            servicer.GetWalletPayments,
            request_deserializer=wallet_dot_requests__pb2.GetWalletPaymentsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetWalletPaymentsReply.SerializeToString,
        ),
        "GetWalletDebts": grpc.unary_unary_rpc_method_handler(
            servicer.GetWalletDebts,
            request_deserializer=wallet_dot_requests__pb2.GetWalletDebtsRequest.FromString,
            response_serializer=wallet_dot_replies__pb2.GetWalletDebtsReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "qbit.WalletService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
